repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.5
    hooks:
      - id: terraform-fmt